language: python
sudo: false

python:
  - "3.5"
  - "nightly" # currently points to 3.6-dev

install: "pip install -r requirements.txt"

script:
  - nosetests-3.4 --with-coverage --cover-package dino -s
  - coverage-3.5 report --omit=env -m

after_success:
  - codecov
